export const items = [
	{
		id: 0,
		name: 'hamburger set',
		price: '1200',
		imageSrc: 'https://via.placeholder.com/256',
		description: 'lorem',
		allergies: ['meat'],
		nutrition: [
			{category: 'calories', amount: '500kCal'},
			{category: 'fat', amount: '100g'},
		],
		setItem: true,
		higlight: false,
		badgeSrc: 'https://via.placeholder.com/64',
	},
	{
		id: 1,
		name: 'cheeseburger set',
		price: '1300',
		imageSrc: 'https://via.placeholder.com/256',
		description: 'lorem',
		allergies: ['meat'],
		nutrition: [
			{category: 'calories', amount: '500kCal'},
			{category: 'fat', amount: '100g'},
		],
		setItem: true,
		higlight: false,
		badgeSrc: 'https://via.placeholder.com/64',
	},
	{
		id: 2,
		name: 'chille cheesburger set',
		price: '1400',
		imageSrc: 'https://via.placeholder.com/256',
		description: 'lorem',
		allergies: ['meat'],
		nutrition: [
			{category: 'calories', amount: '500kCal'},
			{category: 'fat', amount: '100g'},
		],
		setItem: true,
		higlight: true,
		badgeSrc: 'https://via.placeholder.com/64',
	},
	{
		id: 3,
		name: 'hamburger',
		price: '800',
		imageSrc: 'https://via.placeholder.com/256',
		description: 'lorem',
		allergies: ['meat'],
		nutrition: [
			{category: 'calories', amount: '500kCal'},
			{category: 'fat', amount: '100g'},
		],
		setItem: false,
		higlight: false,
		badgeSrc: 'https://via.placeholder.com/64',
	},
	{
		id: 4,
		name: 'cheeseburger',
		price: '900',
		imageSrc: 'https://via.placeholder.com/256',
		description: 'lorem',
		allergies: ['meat'],
		nutrition: [
			{category: 'calories', amount: '500kCal'},
			{category: 'fat', amount: '100g'},
		],
		setItem: false,
		higlight: false,
		badgeSrc: 'https://via.placeholder.com/64',
	},
	{
		id: 5,
		name: 'chille cheesburger',
		price: '1000',
		imageSrc: 'https://via.placeholder.com/256',
		description: 'lorem',
		allergies: ['meat'],
		nutrition: [
			{category: 'calories', amount: '500kCal'},
			{category: 'fat', amount: '100g'},
		],
		setItem: false,
		higlight: false,
		badgeSrc: 'https://via.placeholder.com/64',
	},
]
